1

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -25,34 +25,31 @@ jobs:
         run: dotnet test UnitTest/UnitTest.csproj --logger "trx;LogFileName=test-results.trx"
         shell: cmd
 
-      - name: Upload test results
-        if: success() || failure()
-        uses: actions/upload-artifact@v3
-        with:
-          name: test-results
-          path: test-results.trx
+      # - name: Upload test results
+        # if: success() || failure()
+        # uses: actions/upload-artifact@v3
+        # with:
+        #   name: test-results
+        #   path: UnitTest/TestResults/*.trx
 
-  test-report:
-    name: Generate Test Report
-    needs: unit-tests
-    runs-on: self-hosted
-    steps:
-      - name: Download test results
-        uses: actions/download-artifact@v3
-        with:
-          name: test-results
+  # test-report:
+  #   name: Generate Test Report
+  #   needs: unit-tests
+  #   runs-on: self-hosted
+  #   steps:
+  #     - name: Download test results
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: test-results
 
-      - name: List downloaded files
-        run: dir
-        shell: cmd
-
-      - name: Generate test report
-        uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5
-        with:
-          artifact: test-results
-          name: Unit Test Report
-          path: 'test-results.trx'
-          reporter: dotnet-trx
+  #     # dorny/test-reporter@afe6793191b75b608954023a46831a3fe10048d4
+  #     - name: Generate test report
+  #       uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5
+  #       with:
+  #         artifact: test-results
+  #         name: Unit Test Report
+  #         path: 'test-results.trx'
+  #         reporter: dotnet-trx
 # name: CI Pipeline
 
 # on:
